### ISSUE TITLE
"mvn test" Failed (JDK 11)

### ISSUE THREAD

**Issue by maruTA-bis5** [excella-core/excella-reports#40]
JDK 11環境で`mvn test`を実行すると、下記のログに示すとおり、例外が発生して失敗します。

### 環境
Ubuntu 18.04 on WSL
OpenJDK 11 (openjdk-11 `11~24-1~18.04` from https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa)

※同じ環境でJAVA_HOMEをJDK8に設定した場合は問題なく終了する

### `mvn test` ログ
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.bbreak.excella.reports.AllTestSuite
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.openxml4j.util.ZipSecureFile$1 (file:/home/maruyama/.m2/repository/org/apache/poi/poi-ooxml/3.16/poi-ooxml-3.16.jar) to field java.io.FilterInputStream.in
WARNING: Please consider reporting this to the maintainers of org.apache.poi.openxml4j.util.ZipSecureFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ブック処理結果:シート1=Sheet1,シート2=Sheet2,
ブック処理結果:シート1=Sheet3,
ブック処理結果:シート1=CSheet1,シート2=CSheet2,
ブック処理結果:シート1=Sheet3,
ブック処理結果:シート1=CSheet1,シート2=Sheet2,シート3=CSheet2,シート4=Sheet3,
ブック処理結果:シート1=CSheet2,シート2=Sheet2,シート3=CSheet3,シート4=Sheet3,
ブック処理結果:シート1=CSheet1,
ブック処理結果:シート1=Sheet1,シート2=Sheet2,
ブック処理結果:シート1=Sheet3,
ブック処理結果:シート1=CSheet1,シート2=CSheet2,
ブック処理結果:シート1=Sheet3,
ブック処理結果:シート1=CSheet1,シート2=Sheet2,シート3=CSheet2,シート4=Sheet3,
ブック処理結果:シート1=CSheet2,シート2=Sheet2,シート3=CSheet3,シート4=Sheet3,
ブック処理結果:シート1=CSheet1,
Tests run: 177, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 40.979 sec <<< FAILURE! - in org.bbreak.excella.reports.AllTestSuite
testParseSheetCellObject[1](org.bbreak.excella.reports.tag.RowRepeatParamParserTest)  Time elapsed: 1.183 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.tag.RowRepeatParamParserTest.checkSheet(RowRepeatParamParserTest.java:424)
	at org.bbreak.excella.reports.tag.RowRepeatParamParserTest.testParseSheetCellObject(RowRepeatParamParserTest.java:128)

testParseSheetCellObject[1](org.bbreak.excella.reports.tag.ColRepeatParamParserTest)  Time elapsed: 1.016 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.tag.ColRepeatParamParserTest.checkSheet(ColRepeatParamParserTest.java:397)
	at org.bbreak.excella.reports.tag.ColRepeatParamParserTest.testParseSheetCellObject(ColRepeatParamParserTest.java:125)

testParseSheetCellObject[1](org.bbreak.excella.reports.tag.BlockColRepeatParamParserTest)  Time elapsed: 1.045 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.tag.BlockColRepeatParamParserTest.checkSheet(BlockColRepeatParamParserTest.java:741)
	at org.bbreak.excella.reports.tag.BlockColRepeatParamParserTest.testParseSheetCellObject(BlockColRepeatParamParserTest.java:214)

testParseSheetCellObject[1](org.bbreak.excella.reports.tag.BlockRowRepeatParamParserTest)  Time elapsed: 1.04 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.tag.BlockRowRepeatParamParserTest.checkSheet(BlockRowRepeatParamParserTest.java:731)
	at org.bbreak.excella.reports.tag.BlockRowRepeatParamParserTest.testParseSheetCellObject(BlockRowRepeatParamParserTest.java:213)

testPostParse[1](org.bbreak.excella.reports.listener.RemoveAdapterTest)  Time elapsed: 0.872 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.listener.RemoveAdapterTest.checkSheet(RemoveAdapterTest.java:135)
	at org.bbreak.excella.reports.listener.RemoveAdapterTest.testPostParse(RemoveAdapterTest.java:100)

testPostParse[1](org.bbreak.excella.reports.listener.BreakAdapterTest)  Time elapsed: 1.168 sec  <<< ERROR!
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : class org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream cannot be cast to class java.util.zip.ZipFile$ZipFileInputStream (org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream is in unnamed module of loader 'app'; java.util.zip.ZipFile$ZipFileInputStream is in module java.base of loader 'bootstrap')
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.available(ZipFile.java:479)
	at org.apache.poi.openxml4j.util.ZipSecureFile$ThresholdInputStream.available(ZipSecureFile.java:315)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:84)
	at org.apache.poi.openxml4j.opc.ZipPackagePart.save(ZipPackagePart.java:124)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1543)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:248)
	at org.bbreak.excella.core.util.PoiUtil.writeBook(PoiUtil.java:366)
	at org.bbreak.excella.reports.listener.BreakAdapterTest.checkSheet(BreakAdapterTest.java:129)
	at org.bbreak.excella.reports.listener.BreakAdapterTest.testPostParse(BreakAdapterTest.java:105)


Results :

Tests in error: 
  RowRepeatParamParserTest.testParseSheetCellObject:128->checkSheet:424 » OpenXML4JRuntime
  ColRepeatParamParserTest.testParseSheetCellObject:125->checkSheet:397 » OpenXML4JRuntime
  BlockColRepeatParamParserTest.testParseSheetCellObject:214->checkSheet:741 » OpenXML4JRuntime
  BlockRowRepeatParamParserTest.testParseSheetCellObject:213->checkSheet:731 » OpenXML4JRuntime
  RemoveAdapterTest.testPostParse:100->checkSheet:135 » OpenXML4JRuntime Fail to...
  BreakAdapterTest.testPostParse:105->checkSheet:129 » OpenXML4JRuntime Fail to ...

Tests run: 177, Failures: 0, Errors: 6, Skipped: 0
```

**Comment by maruTA-bis5** [comment]
POI 4.0で修正されている以下の問題と思われます。
https://bz.apache.org/bugzilla/show_bug.cgi?id=62187

**Comment by maruTA-bis5** [comment]
#45 でPOI 4.1.1に更新されており、実際にJDK 11で`mvn test`を実行しても同様のエラーは発生しないためクローズします
