### ISSUE TITLE
$BC[]タグもしくは$BR[]タグで指定した範囲内にExcel関数が入力されたセルがあると例外が発生します。

### ISSUE THREAD

**Issue by tooteeya** [excella-core/excella-reports#57]
$BC[]タグもしくは$BR[]タグで指定した範囲内にExcel関数（SUMなど）が入力されたセルがあると、以下の例外が発生します。
```
Message[java.lang.IllegalArgumentException: Calling Cell.setCellType(CellType.FORMULA) is illegal. Use setCellFormula(String) directly.] Cause[java.lang.IllegalArgumentException: Calling Cell.setCellType(CellType.FORMULA) is illegal. Use setCellFormula(String) directly.] 
	at org.bbreak.excella.reports.tag.BlockRowRepeatParamParser.parse(BlockRowRepeatParamParser.java:515)
	at org.bbreak.excella.reports.tag.BlockRowRepeatParamParser.parse(BlockRowRepeatParamParser.java:51)
```

利用しているライブラリは以下です。
poi-4.1.1.jar
~~excella-reports-1.1.jar~~
excella-reports-2.0.jar

**Comment by maruTA-bis5** [comment]
@tooteeya `excella-reports-1.1.jar`は`poi-4.1.1.jar`と互換性がありませんが、このバージョンの組み合わせで使っているのですか？

**Comment by tooteeya** [comment]
すみません、別のプロジェクトパッケージに入っているものと間違えていました。
例外が発生したのは`excella-reports-2.0.jar`です。

**Comment by maruTA-bis5** [comment]
ExCella Reports v2.1にてリリースしました。
